language: rust
sudo: false

DEPLOY_TO_GITHUB:
  before_deploy: &1
  - git config --local user.name "Domenico Shura"
  - git config --local user.email "shura1991@gmail.com"
  - name="spotify-dbus-bridge-$TRAVIS_TAG-$TARGET"
  - mkdir $name
  - cp target/$TARGET/release/spotify-dbus-bridge $name/
  - tar czvf $name.tar.gz $name
  deploy: &2
    provider: releases
    api_key:
      secure: CSoVERpSmz99qD2tbvBFQq+11Zw6Iznwa36K+Jv+tMrkpwN1iwmHRXal/xy0Bgrn35vGZxdPzLKJHX5OZIyiccoOVidEPvl1cRLQiyx5ftZysak9OrNtau+D5ukdVFgq+vh6+V58fePjLuP8BN6goHeyRHg6DH8JEXgt6orcyerb6x375tuXmtrK7V7xUs2uzsvXhgPdcgRYXHkvoMPXpi/wSOngYZuvVLgam7gMhwo9YEaAW5Rh17X7BWhBfx0J1Gq1H7RLRYnhp4a2NehTakV3FlZZxL8Qfp9J0hv5MiClvpc0AKByFjDZbJU93wOFQsLAKkV/BwxkqV21GYB25t8PSai4o/fFXMHZrBqJGRR3NIwlWx4nWfMWvg/u2fy1qwgDRbmgFJfXENBVOSsaq+9mhz8q69UsjjHhZf+x9zZMyAyX8IaEnhFzsml6ra5STcdW2TFlFCjp1eLs1YchOzEs8IDmBjx2HkJhYSso16kMy7lbi0O86ghN249qotVamyKgRt0lhPNj9R01QIgA3iFr+156PwS6rqVXhDScy0gg4+ABe5MkFhZhVUwAs9CObEbYrQFzjAL79HVVknRFLj0u0/w+g3rkEFiQnp70UDd8QIFDUaZxD2Xeh/kI3WanYvUtbWaW4IzPEo8v0IMHHDVuJMtQEdf/jyvPK+M9dwM=
    file: spotify-dbus-bridge-$TRAVIS_TAG-$TARGET.tar.gz
    skip_cleanup: true
    on:
      repo: shurizzle/rust-macos-spotify-dbus-bridge
      branch: master
      tags: true

matrix:
  include:
  - name: macOS Binary
    env: MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin
    os: osx
    addons:
      homebrew:
        packages:
        - dbus
        update: true
    rust: nightly
    script: cargo build --release --target $TARGET --locked
    install: true
    before_deploy: *1
    deploy: *2
notifications:
  email:
    on_success: never
