[package]
name = "spotify-dbus-bridge"
version = "0.0.2"
authors = ["Domenico Shura <shura1991@gmail.com>"]
edition = "2018"

[dependencies]
macos-spotify = "0.0.3"
macos-open = "0.0.3"
dbus = "0.6.4"
